# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77968e843af6a6615cde2edd6be6bc38463a921cb020a99afa455258cf8533c75eaaa74581edee8a55a521eaceaf77bfb5c6fdea19092ca13c24b542ec4cf8de

test:
  secret_key_base: b06509914444715c46a8e1ec1e4c86e1389078b0e29480d54af50eb885b431ae1fcbed5f71ef4e67d5c871341c040839cf5c21602d371c1b2cd737ad37c3560b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
